num_feats: [
shadowbandwm_avg,
uva_avg,
winddir_d1_wvt,
winddir_sd1_wvt,
measured_co2,
dnicalc_avg,
rh,
ws_ms_s_wvt,
measured_rh,
shadowwm_avg,
airtc_avg,
sunwm_avg,
measured_pm2.5,
measured_t,
measured_pm10,
trackerwm_avg,
batt24v_min,
bp_mb_avg,
uvb_avg,
battv_min,
measured_pm1.0
]
cat_feats: [
break_time_1,
school_day_1,
classroom_type_1,
classroom_type_2,
classroom_type_3,
classroom_type_4,
classroom_type_5,
classroom_category_1,
school_hours_1,
power_on_1,
power_on_2
]
target_feature: outdoor_temperature