model:
  type: Informer
  args:
    configs_path: "src/models/transformer/configs.yaml"
    device: 'cpu'

train:
  type: TimeSeriesTransformerDataset
  args:
    data_path: 'dataset/train.csv'
    configs_path: 'dataset/configs.yaml'
    augment: false
    device: 'cpu'

valid:
  type: TimeSeriesTransformerDataset 
  args:
    data_path: 'dataset/valid.csv'
    configs_path: 'dataset/configs.yaml'
    augment: false
    device: 'cpu'

test:
  type: TimeSeriesTransformerDataset
  args:
    data_path: 'dataset/test.csv'
    configs_path: 'dataset/configs.yaml'
    augment: false
    device: 'cpu'

optimizer:
  type: AdamW
  args:
    lr: 0.001

criterion:
  type: HuberLoss
  args: 
    reduction: mean
    delta: 1.0

schedulers:
  type: ReduceLROnPlateau
  args: {}

device: cpu
num_epochs: 40
batch_size: 1024
output_dirpath: 'results/informer_last'