model:
  type: FTTransformer
  args:
    configs_path: "src/models/transformer/configs.yaml"
    device: 'cpu'

train:
  type: ThermoTransformerDataset
  args:
    data_path: 'tmp/train.csv'
    configs_path: 'tmp/configs.yaml'
    device: 'cpu'

valid:
  type: ThermoTransformerDataset
  args:
    data_path: 'tmp/valid.csv'
    configs_path: 'tmp/configs.yaml'
    device: 'cpu'

optimizer:
  type: Adam
  args:
    lr: 0.001

criterion:
  type: MSELoss
  args: {}

schedulers:
  type: StepLR
  args:
    step_size: 10
    gamma: 0.1

device: cpu
num_epochs: 1
batch_size: 16
